# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "nvme" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a4ee920a-6539-4c78-aa5b-a61bf27c002d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BAA3-0464";
      fsType = "vfat";
    };

  fileSystems."/mnt/coreos_drive" =
    { device = "/dev/disk/by-uuid/bf1f6234-7f65-48a2-b7f8-4eab532eed90";
      fsType = "ext4";
    };

  fileSystems."/var/lib/radarr" =
    { device = "loutrepool/var/radarr";
      fsType = "zfs";
    };

  fileSystems."/var/lib/slimserver" =
    { device = "loutrepool/var/slimserver";
      fsType = "zfs";
    };

  fileSystems."/var/lib/transmission" =
    { device = "loutrepool/var/transmission";
      fsType = "zfs";
    };

  fileSystems."/var/lib/grafana" =
    { device = "loutrepool/var/grafana";
      fsType = "zfs";
    };

  fileSystems."/var/lib/emby/ProgramData-Server" =
    { device = "loutrepool/var/emby";
      fsType = "zfs";
    };

  fileSystems."/var/db/influxdb" =
    { device = "loutrepool/var/influxdb";
      fsType = "zfs";
    };

  fileSystems."/var/lib/duplicati" =
    { device = "loutrepool/var/duplicati";
      fsType = "zfs";
    };

  fileSystems."/mnt/medias" =
    { device = "loutrepool/medias";
      fsType = "zfs";
    };

  fileSystems."/exports/steam" =
    { device = "loutrepool/steam";
      fsType = "zfs";
    };

  fileSystems."/var/lib/acme" =
    { device = "loutrepool/var/acme";
      fsType = "zfs";
    };

  fileSystems."/var/lib/syncthing" =
    { device = "loutrepool/var/syncthing";
      fsType = "zfs";
    };

  fileSystems."/var/vmail" =
    { device = "loutrepool/var/vmail";
      fsType = "zfs";
    };

  fileSystems."/var/dkim" =
    { device = "loutrepool/var/dkim";
      fsType = "zfs";
    };

  fileSystems."/var/sieve" =
    { device = "loutrepool/var/sieve";
      fsType = "zfs";
    };

  fileSystems."/var/lib/sonarr" =
    { device = "loutrepool/var/sonarr";
      fsType = "zfs";
    };

  fileSystems."/var/lib/postgresql" =
    { device = "loutrepool/var/postgresql";
      fsType = "zfs";
    };

  fileSystems."/var/lib/matrix-synapse" =
    { device = "loutrepool/var/matrix-synapse";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/var/swapfile"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
